#ifndef WINDOWSTYLE_H
#define WINDOWSTYLE_H
#define BORDERLINE_COLOR 0
#define TOPBAR_COLOR 0x5ACB
#define TOPBAR_HEIGHT 20
#define BOTTOMBAR_COLOR 0x5ACB
#define BOTTOMBAR_HEIGHT 20
#define TITLE_OFFSET_X 25
#define TITLE_OFFSET_Y 2
#define TITLE_COLOR 0xFFFF
#endif
